### PR TITLE
websocket impl for servlet example

### PR DESCRIPTION
**Pull request by barong**

### CODE REVIEW

**Comment by RuedigerMoeller** [comment]
oops, there are too many conflicts. I got a websockets <=> kontraktor remoting prototype working, just need to add proper config handling, refactor out common code from the sample and somehow get a servlet and websockets to act as one, as typically one uses websockets for ajax-style communication and implements file redirection/handling inside a servlet

**Comment by barong** [comment]
Hi,
servlet http long polling example doesn't work now - js error "session.tell is not a function",
could you please look at it?
then I can make more clean PR if it still needs

**Comment by RuedigerMoeller** [comment]
Hi, I'm currently busy providing React support (requires some major changes), so some sample might break temporary. 
For servlet I plan to only support (adaptive) long poll as this scales much better than websockets and the offical java websocket API does not integrate well with the servlet api..

**Comment by RuedigerMoeller** [comment]
fixed the sample, login now returns [actorproxy, authresult] to ease app init (else an app requires a second request (full round trip) to load initial data).
Note it might take weeks until a stable 3.34 release is public, moving things :)

**Comment by barong** [comment]
thank you =)

**Comment by barong** [comment]
Hi RuedigerMoeller,
I'm not sure that I'm right, but websocket servlet example looks like it's working with this PR

**Comment by RuedigerMoeller** [comment]
Nice, will review later™ , thanks for helping out in advance :)

**Comment by RuedigerMoeller** [comment]
wow that looks good .. why did you remove the weakreference, i assume this was in there beacuse of memleaks (the originaö code has been pasted from undertow websocket adapter)

**Comment by RuedigerMoeller** [comment]
thank you

**Comment by barong** [comment]
hi, I don't know why, but with weakreference it doesn't work, it always is null. Is there any other place where we can remove link to sink to prevent memory leak?

**Comment by RuedigerMoeller** [comment]
ok, so this is probably different here, I can't remember the exact scenario I introduced the weakref ..

**Pull request merged**
